name: Actualizar Raindrop Aleatorio

on:
  schedule:
    - cron: '*/10 * * * *' 
  workflow_dispatch: 

jobs:
  update:
    runs-on: ubuntu-latest
    
    # SOLUCIÓN 1: Añadir permisos de escritura para el token
    permissions:
      contents: write 
      
    steps:
      - name: Checkout del código (Usando la rama principal)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main 
          
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script y obtener Raindrop
        run: node fetchRandomRaindrop.js
        env:
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }} 

      - name: Subir cambios al repositorio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Actualizar Raindrop aleatorio
          # SOLUCIÓN 2: Renombrar 'files' a 'file_pattern'
          file_pattern: random_url.json