name: Actualizar Raindrop Aleatorio

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo (Usando la rama Raindrop)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: Raindrop 
          
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script y obtener Raindrop
        run: node fetchRandomRaindrop.js
        env:
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }} 

      - name: Subir cambios al repositorio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Actualizar Raindrop aleatorio
          files: random_url.json 
