name: Actualizar Raindrop Aleatorio

on:
  schedule:
    # 1) Se ejecuta automáticamente cada 10 minutos
    - cron: '*/10 * * * *' 
  workflow_dispatch: 

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código (Usando la rama principal)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 1) Cambiado de 'Raindrop' a 'main'
          ref: main 
          
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script y obtener Raindrop
        run: node fetchRandomRaindrop.js
        env:
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }} 

      - name: Subir cambios al repositorio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Actualizar Raindrop aleatorio
          files: random_url.json